server:
  port: 8081
  servlet:
    context-path: /ar_demo/
spring:
  profiles:
    active: postgres

---
spring:
  profiles: postgres
  application:
    name: ar_demo
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        provider_disables_autocommit: false
    #generate-ddl: true
    #show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/ar?createDatabaseIfNotExist=true
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    autoCommit: false
    hikari:
      connection-timeout: 20000
      maximumPoolSize: 10
    max-wait: 10000

---
spring:
  profiles: mysql
  application:
    name: ar_demo
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        provider_disables_autocommit: false
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    #generate-ddl: true
    #show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/ar_demo?createDatabaseIfNotExist=true
    #username: postgresuser
    username: root
    password: imaninshu1@
    hikari:
      connection-timeout: 20000
      maximumPoolSize: 10
    max-wait: 10000
logging:
  level.root: info
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
