server:
  port: 8081
  servlet:
    context-path: /patient360/
spring:
  profiles:
    active: postgres

---
spring:
  profiles: postgres
  application:
    name: patient-360
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        provider_disables_autocommit: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/ar?createDatabaseIfNotExist=true
    #username: postgresuser
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    autoCommit: false
    hikari:
      connection-timeout: 20000
      maximumPoolSize: 10
    max-wait: 10000

---
spring:
  profiles: mysql
  application:
    name: patient-360
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        provider_disables_autocommit: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/patient360?createDatabaseIfNotExist=true
    #username: postgresuser
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    autoCommit: false
    hikari:
      connection-timeout: 20000
      maximumPoolSize: 10
    max-wait: 10000

logging:
  level.root: error
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
